(require 'languages/core)
(require 'languages/markdown)
(require 'languages/go)
(require 'languages/ruby)
(require 'languages/javascript)
(require 'languages/java)
(require 'languages/kotlin)
(require 'languages/python)
(require 'languages/rust)

(provide 'init-languages)
